# Site settings
title: LeaveShine|骊醒的个人blog
description: '腰有十文，必振衣作响；得见美人，必急纳入帐。此我求学之道也。'
url: 'http://leaveshine.me'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: '瞿骊醒'
  email: qulixing888@163.com
  twitter_username: none
  facebook_username: 瞿骊醒
  github_username:  leaveshine
  linkedin_username:  瞿骊醒

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
